apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: gcr.io/vast-fuze-308111/example:e33e1fa
        name: example
        ports:
        - containerPort: 8000